version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=vina1998
      - MYSQL_DATABASE=spring_docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=vina1998
  springboot-docker-container:
    image: springboot-docker-container
    container_name: spring-boot-app
    ports:
      - 8086:8086
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone